services:
  hotspot:
    build:
      context: .
      dockerfile: hotspot.Dockerfile
    network_mode: host
    privileged: true
    restart: unless-stopped
    depends_on:
      - checkin

  checkin:
    build:
      context: ..
      dockerfile: checkin.Dockerfile
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - tour-net

networks:
  tour-net:
    name: tour-net
    driver: bridge
