services:
  hotspot:
    user: "0:0"
    build:
      context: .
      dockerfile: hotspot.Dockerfile
    network_mode: host
    privileged: true
    restart: unless-stopped
    #depends_on:
    #  - checkin

  checkin:
    build:
      context: ..
      dockerfile: checkin.Dockerfile
    restart: unless-stopped
    ports:
      - "5001:5001"
    #networks:
     # - tour-net
    depends_on:
      - meleenium
      - slippi-ftp
    network_mode: host
  
  meleenium:
    build:
      context: ../services/meleenium
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    environment:
      STARTGG_BEARER: "${STARTGG_BEARER}"
      STARTGG_EVENT_ID: "${STARTGG_EVENT_ID}"
  
  slippi-ftp:
    build:
      context: ../services/sharlots-slippi-ftp-server
      dockerfile: Dockerfile
      args:
        - FSURL=slippi-ftp.com/slp-replays
        - NAME=Konga-Line
        - USEHTTPS=FALSE
    container_name: slippi-ftp
    cap_add:
      - NET_BIND_SERVICE
    network_mode: "host"
    volumes:
      - ./slp-files:/web/sharlot/public_html/slp-files
    restart: unless-stopped
