services:
  hotspot:
    build:
      context: .
      dockerfile: hotspot.Dockerfile
    network_mode: host
    privileged: true
    restart: unless-stopped
    depends_on:
      - checkin

  checkin:
    build:
      context: ..
      dockerfile: checkin.Dockerfile
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - tour-net
    depends_on:
      - meleenium

  meleenium:
    build:
      context: ../services/meleenium
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      STARTGG_BEARER: "${STARTGG_BEARER}"
      STARTGG_EVENT_ID: "${STARTGG_EVENT_ID}"
    networks:
      - tour-net

networks:
  tour-net:
    name: tour-net
    driver: bridge
